### ISSUE TITLE
raygui remove function for GetCodepointNext

### ISSUE THREAD

**Issue by schveiguy** [schveiguy/raylib-d#32]
This interferes with the new version inside raylib that was not in 4.2.0.

**Comment by 0xEAB** [comment]
can confirm, breaks out-of-the-box experience after upgrade to 4.5:
```
ld: error: duplicate symbol: GetCodepointNext
>>> defined at raygui.d:4348 (../../../.dub/packages/raylib-d-4.5.0/raylib-d/source/raygui.d:4348)
>>>            .dub/build/application-debug-linux.posix-x86_64-ldc_v1.31.0-…/my-game.o:(GetCodepointNext)
>>> defined at rtext.c
>>>            rtext.o:(.text+0xB697) in archive libraylib.a
```

**Comment by schveiguy** [comment]
Try raylib 4.5.1

**Comment by 0xEAB** [comment]
oh thanks, didn’t see that version :)
